name: Run Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.3.1
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        sudo apt install rsync -y
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements/dev .
    - name: Launch tests
      run: |
        pytest ./tests --cov-report=xml --cov=checksum

    - name: Upload code coverage report
      uses: codecov/codecov-action@v1
      with:
        if: success()
        token: ${{ secrets.CODECOV_TOKEN }}
